grails-app/controllers/agro/BuyController.groovy
package agro

import agro.dto.CheckableString
import grails.plugin.cookie.CookieService
import grails.plugin.springsecurity.SpringSecurityService
import grails.plugin.springsecurity.annotation.Secured

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
class BuyController {
    CookieService cookieService
    SaleService saleService
    ProductService productService
    UserService userService
    SpringSecurityService springSecurityService


    def index() {
        User curUser = springSecurityService.currentUser as User
        List<CheckableString> checkableProducts = []
        List<String> productParams = []
        def productsNames = productService.list()

        if (params['produits[]'] != null) {
            if (params['produits[]'] instanceof String) {
                productParams.push(params['produits[]'] as String)
            } else {
                def temp = params['produits[]'] as List<String>
                temp.forEach() {
                    productParams.push(it)
                }
            }
        }

        productsNames.forEach() {
            def temp = new CheckableString(string: it.name, checked: false);
            if (productParams.contains(it.name)) {
                temp.checked = true;
            }
            checkableProducts.push(temp);
        }

        params.max = Math.min(params.max as Integer ?: 10, 100)
        params.remove('produits[]')

        def a = saleService.getValidSales(params.page == null ? 1 : params.page as Integer, params.max as Integer,curUser);


        if (!productParams.isEmpty()) {
            a = saleService.getValidSalesByProducts(productParams, params.page as Integer, params.max as Integer,curUser)
        }

        String cookie = cookieService.getCookie('cart')
        List<String> cart = null
        if (cookie != null && !cookie.isEmpty()) {
            cart = cookie.split(/_/)
        }


        Cart mostRecentCart = null
        if (curUser != null) {
            def queriesRes = userService.getMostRecentCart(curUser)
            if (!queriesRes.isEmpty()) {
                mostRecentCart = queriesRes.first() as Cart
                if (cart != null) { // if existent cookie
                    if (mostRecentCart.sales == null) {
                        mostRecentCart.sales = []
                    }
                    for (i in 0..<cart.size()) {
                        def sale = Sale.get(cart[i] as long)
                        if (!mostRecentCart.sales.contains(sale)) {
                            mostRecentCart.sales.add(sale)
                        }
                    }
                }
                cart = []
                for (i in 0..<mostRecentCart.sales.size()) {
                    def sale = mostRecentCart.sales[i]
                    if (sale.saleState != SaleState.CREATED.ordinal()) { // if sale deactivated or sold
                        mostRecentCart.removeFromSales(sale)
                    } else {
                        cart.add(mostRecentCart.sales[i].id as String)
                    }
                }
                cookieService.setCookie('cart', cart.join('_'), 1, '/')
                mostRecentCart.save(flush: true, failOnError: true)
            } else {
                Cart newCart = new Cart();
                newCart.sales = []
                curUser.addToCarts(newCart);
                if (cart != null) { // if existent cookie
                    for (i in 0..<cart.size()) {
                        def sale = Sale.get(cart[i] as long)
                        if (sale.saleState != SaleState.CREATED.ordinal()) {
                            newCart.sales.add(sale)
                        }
                    }
                }
                cart = []
                for (i in 0..<newCart.sales.size()) {
                    cart.add(newCart.sales[i].id as String)
                }
                newCart.save(flush: true, failOnError: true)
                cookieService.setCookie('cart', cart.join('_'), 1, '/')
            }
        }

        respond a, model: [products: checkableProducts, sales: a, page: params.page as Integer, cart: cart]
    }
}

grails-app/views/buy/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: HP
  Date: 28/08/2022
  Time: 09:07
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>${controllerName}</title>
</head>

<body>
<div class="container">
    <div class="row mt-3">
        <div class="left-product-list col-lg-3 p-0">
            <div class="head btn w-100 not-rounded text-uppercase bold-text">Produits disponibles</div>
            <g:form controller="buy">
                <ul class="products-list buy p-0">
                    <g:each var="product" in="${products}">
                        <li class="product-item">
                            <input onchange="resetPage()" type="checkbox" name="produits[]"
                                   value="${product.string}" ${product.checked ? "checked" : ''}>
                            <label>${product.string}</label>
                        </li>
                    </g:each>
                    <li><br/></li>
                    <li><br/></li>
                    <li><br/></li>
                </ul>
                <input id="page" type="hidden" name="page" value="${page as Integer ?: 1}">
                <input type="hidden" name="max" value="10">

                <div class="scrollIndicator"></div>
                <g:submitButton class="btn green-btn not-rounded" name="submit" value="FILTRER"/>
            </g:form>
        </div>

        <div class="col-lg-9">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th style="text-align: left" scope="col">Vendeur</th>
                    <th style="text-align: center" scope="col">Produit</th>
                    <th style="text-align: center" scope="col">Prix/Kg(Ar)</th>
                    <th style="text-align: center" scope="col">Quantité</th>
                    <th style="text-align: center" scope="col">Total(Ar)</th>
                    <th style="text-align: center" scope="col">Date</th>
                    <th style="text-align: center" scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <g:each var="sale" in="${sales}">
                    <tr>
                        <th style="text-align: right" scope="row">${sale.user.username}</th>
                        <td>${sale.product.name}</td>
                        <td align="right"><g:formatNumber number="${sale.price}" format="###,###"/></td>
                        <td align="right"><g:formatNumber number="${sale.quantity}" /></td>
                        <td align="right"><g:formatNumber number="${sale.quantity * sale.price}" format="###,###"/></td>
                        <td><g:formatDate format="dd/MM/yyyy" date="${sale.dateCreated}"/></td>
                        <td>
                            <button style="${cart == null || !(cart as List<String>).contains(sale.id as String) ? "" : "display: none"}"
                                    id="add-to-cart${sale.id}"
                                    onclick="addToCart(${sale.id}, 'add-to-cart${sale.id}', 'remove-from-cart${sale.id}')"
                                    type="button" class="btn btn-primary btn-sm">Ajouter</button>
                            <button style="${cart == null || !(cart as List<String>).contains(sale.id as String) ? "display: none" : ""}"
                                    onclick="removeFromCart(${sale.id}, 'add-to-cart${sale.id}', 'remove-from-cart${sale.id}')"
                                    id="remove-from-cart${sale.id}" type="button"
                                    class="btn btn-secondary btn-sm">Retirer</button>
                        </td>
                    </tr>
                </g:each>
                </tbody>
            </table>
            <g:if test="${page != null}">
                <nav aria-label="...">
                    <ul class="pagination">
                        <li class="page-item ${page == 1 ? 'active' : ''}"><a
                                onclick="changePage(${page == 1 ? 1 : page-1})"
                                class="page-link"
                                href="#">${page == 1 ? 1 : page - 1}</a></li>
                        <li class="page-item ${page != 1 ? 'active' : ''}">
                            <a onclick="changePage(${page == 1 ? 2 : page})" href="#" class="page-link">
                                ${page == 1 ? 2 : page}
                            </a>
                        </li>
                        <li class="page-item"><a onclick="changePage(${page == 1 ? 3 : page+1})" class="page-link"
                                                 href="#">${page == 1 ? 3 : page + 1}</a></li>
                    </ul>
                </nav>

                <g:javascript>
                    function changePage(page) {
                        $("#page").val(page);
                        $("#submit").click();
                    }
                </g:javascript>
            </g:if>
        </div>
    </div>





    <g:javascript>
        function resetPage() {
            $("#page").val(1);
        }
    </g:javascript>
</div>
</body>
</html>